### ISSUE TITLE
[lang] yaml 1.1 vs yaml 1.2 support

### ISSUE THREAD

**Issue by Naatan** [vmware-tanzu/carvel-ytt#146]
My yaml source contains:

```
on:
  push:
    branches:
      - master
  pull_request:
    - master
```

Which gets compiled as:

```
true:
  push:
    branches:
    - master
  pull_request:
  - master
```

**Comment by cppforlife** [comment]
currently ytt uses yaml library that follows yaml 1.1 spec i believe. in that spec `on` is equivalent to `true`. to make this work youll have to do something like this:

```yaml
"on":
  push:
    branches:
      - master
  pull_request:
    - master
```
